from IterativeBruteForce import IterativeBruteForce
from MatrixAlgorithmBase import MatrixAlgorithmBase
from MatrixHighestPoints import MatrixHighestPoints
from MatrixHighestPointsLowestPlayers import MatrixHighestPointsLowestPlayers
